### ISSUE TITLE
EF - update-database

### ISSUE THREAD

**Issue by thyme51** [ErikEJ/CloudBurstDemo#2]
Hi Erik,

Thanks again for your code sample and I reviewed your talk [Look ma no password](https://www.youtube.com/watch?v=1FRsuLVeQr0) and this time implemented in my dev environment.

Running on a clean database, I needed to run Update-Database (from Package Manager Console) so I had to create a new ConnectionString i appsettings.json:

    "DefaultDevConnection": "Server=tcp:dev-sql-xxxx.database.windows.net;Database=jrt51;Authentication=Active Directory Default",

Also, I chose to go with a "Group" in bicep/IaC":

 administrators: {
      principalType: 'Group'
      administratorType: 'ActiveDirectory'
      azureADOnlyAuthentication: true
      login: sqlAdministratorLogin
      sid: sqlAdministratorLoginId
      tenantId: subscription().tenantId
   }    

This way I@atmydomain.com and my "managed identity" are administrators:

But here is the questions:
- I shouldn't really add the managed identity as SqlAdmin - it gets its required permissions via the "configure.ps1" script, right?
- Note, I create a ConnectionString "DefaultDevConnection" - but should I just keep that one in my local appsettings.json? In my appService I have "Data Source=tcp:dev-sql-xxxxi.database.windows.net,1433;Initial Catalog=jrt51;Connection Timeout=60;Authentication=Active Directory Managed Identity;Encrypt=true;User Id=34768334-xxxx-4169-b62f-58a2ee7428c8" but sometimes I just want to use "Server=(localdb)\\mssqllocaldb".
What are your recommendations for an effective DEV setup?

Best regards 
Jørgen

**Comment by ErikEJ** [comment]
>> I shouldn't really add the managed identity as SqlAdmin - it gets its required permissions via the "configure.ps1" script, right?

Correct, you should give "yourself" (the DBA) and your pipeline account admin access, not the managed identity.

>> Note, I create a ConnectionString "DefaultDevConnection" - but should I just keep that one in my local appsettings.json?

Anything in app configuration (which becomes environment variables) overrides anything in the appsetttings.json files. So fine to add something useful locally in appSetting.json (or in secrets.json if there are passwords present)
